global:
  marketplace-ami: true
  owner: batrahs@amazon.com
  qsname: quickstart-sap-hana-ha
  regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - ca-central-1
    - eu-central-1
    - eu-west-1
    - sa-east-1
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
  reporting: true
 
tests:
  quickstart-sap-hana-ha-newVPC:
    regions:
      - ap-southeast-2
    parameter_input: SAP_HANA_HA_Master_New_VPC_Input.json
    template_file: SAP_HANA_HA_Master_New_VPC.yaml
